language: cpp
compiler:
  - gcc
  - clang

before_install: export CC=${REAL_CC} CXX=${REAL_CXX}
# before_install: git submodule update --init --recursive

## Install prerequisites
install:
  - sudo apt-get install boost 


script: cmake -DCMAKE_C_COMPILER=CC -DCMAKE_CXX_COMPILER=CXX && make && make test
