language: cpp
compiler:
  - gcc
  - gcc

## Install prerequisites
install: 
        - sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 16126D3A3E5C1192
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y 
        - sudo apt-get update -qq
        #- sudo apt-get install -qq libboost1.48-all-dev        
        - git clone https://github.com/mirror/boost/tree/master/boost
        - cp -rf ./boost /usr/local/include/boost
        - sudo apt-get install -qq gcc-4.8        
        - sudo apt-get install -qq g++-4.8        
script: cmake -DCMAKE_C_COMPILER=gcc-4.8 -DCMAKE_CXX_COMPILER=$CXX && make && make test && ./test
