language: cpp
compiler:
  - clang

before_install: 
        - svn co http://llvm.org/svn/llvm-project/libcxx/trunk/include libcxx_include 
        - pwd
        - export CPATH=$CPATH;$(pwd)\libcxx_include
        - echo $CPATH

## Install prerequisites
install: 
        - sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 16126D3A3E5C1192
        - sudo apt-get update -qq
        - sudo apt-get install -qq libboost-all-dev
        - sudo apt-get install -qq libclang-dev
  
script: cmake -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX && make && make test
