language: cpp
compiler:
  - gcc
  - clang

before_install: export CC=${REAL_CC} CXX=${REAL_CXX}
# before_install: git submodule update --init --recursive

## Install prerequisites
install: 
  - sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 16126D3A3E5C1192
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-all-dev
  
script: cmake -DCMAKE_C_COMPILER=CC -DCMAKE_CXX_COMPILER=CXX && make && make test
